version: "3"
services:
  db:
   image: mariadb:10.2.8
   ports:
     - 3306:3306
   environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=oj
    - MYSQL_USER=user # optional
    - MYSQL_PASSWORD=1234 # optional
   volumes:
     - /mysql:/var/lib/mysql  # data storage path
     - /mariadb.conf.d:/etc/mysql/mariadb.conf.d  # config file. set encoding : utf8mb4_bin

  judgerserver:
   image: registry.cn-hangzhou.aliyuncs.com/jinmingyi/judgerserver
   volumes:
     - /ojdata:/ojdata # problem test data path
   ports:
     - 12345:12345
   environment:
    - SERVICE_PORT=12345
    - OJ_BACKEND_CALLBACK=http://onlinejudge:8080/judge/callback

  onlinejudge:
   image: registry.cn-hangzhou.aliyuncs.com/jinmingyi/onlinejudge
   depends_on:
    - db
   ports:
     - 80:8080
   volumes:
     - /onlinejudge:/onlinejudge # log files
   environment:
   - MYSQL_USER=jinmy
   - MYSQL_PASSWORD=1234
   - MYSQL_URL=db:3306/oj