version: "3"
services:
  judgerserver:
    image: registry.cn-hangzhou.aliyuncs.com/jinmingyi/judgerserver
    container_name: judger
    volumes:
      - /var/judge/ojdata:/ojdata # problem test data path
    ports:
      - 12345:12345
      - 8000:8000
    restart: always
    environment:
      - SERVICE_PORT=12345
      - OJ_BACKEND_CALLBACK=http://172.17.0.1:8888/judge/callback
      - TZ=Asia/Shanghai
      - LC_ALL=C