spring:
  datasource:
    username: jinmy
    password: 1234
    url: jdbc:mysql://localhost:3306/cslearn?serverTimezone=GMT%2B8&useUnicode=yes&characterEncoding=UTF-8
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  #  mvc:
  #    view:
  #      suffix: .html
  #  resources:
  #    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    encoding: utf-8
    cache: true
    mode: HTML
    check-template: false
  config:
    additional-location: onlinejudge
  servlet:
    multipart:
      max-file-size: 3050MB
      max-request-size: 3050MB


#
#logging:
#  path: onlinejudge/log
#
onlinejudge:
  judgerhost:
    - http://localhost:12345/judge
  #    - http://localhost:8001/judge
  #    - http://localhost:8002/judge
  #    - http://localhost:8003/judge
  #    - http://localhost:8004/judge
  #    - http://localhost:6000/judge
  c:
    src: main.c
    seccomp_rule: c_cpp
    run_command: ./main
    compile_command: /usr/bin/gcc -DONLINE_JUDGE -fno-tree-ch -O2 -Wall -std=c99 main.c -lm -o main
    memory_limit_check_only: 0
  cpp:
    src: main.cpp
    seccomp_rule: c_cpp
    run_command: ./main
    compile_command: /usr/bin/g++ -DONLINE_JUDGE -fno-tree-ch -O2 -Wall -std=c++14 main.cpp -lm -o main
    memory_limit_check_only: 0
  go:
    src: main.go
    compile_command: gccgo -g -Wall main.go -o main
    run_command: main
    memory_limit_check_only: 0
    seccomp_rule: general
  java:
    src: Main.java
    run_command: /usr/bin/java -Djava.security.manager -Dfile.encoding=UTF-8 -Djava.awt.headless=true Main
    compile_command: /usr/bin/javac Main.java -encoding UTF8
    memory_limit_check_only: 1
  python2:
    src: main.py
    run_command: /usr/bin/python main.pyc
    compile_command: /usr/bin/python -m py_compile main.py
    memory_limit_check_only: 0
    seccomp_rule: general
  python3:
    src: main.py
    run_command: /usr/bin/python3 __pycache__/main.cpython-36.pyc
    compile_command: /usr/bin/python3 -m py_compile main.py
    memory_limit_check_only: 0
    seccomp_rule: general


server:
  tomcat:
    max-threads: 2000
    max-connections: 20000
    min-spare-threads: 30
